name: generators
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  build: ^2.4.1
  built_value_generator: ^8.9.0
  source_gen:  ^1.5.0
  analyzer: 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  
flutter:
